version: '3.4'
services: 
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fib-api
    ports:
      - 3000:8000
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:  
      - 6379:6379