version: '3.4'
services: 
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fib-api
    ports:
      - 3000:8000
    networks:
      - prod
    depends_on:
      - "redis"

  redis:
    image: redis
    container_name: redis
    networks:
      - prod
    ports:  
      - 6379:6379

networks:
  prod:
    driver: bridge