apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis5
spec:
  - name: redis
    image: "redis:alpine"
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379

volumes:
- name: redis-storage
  emptyDir: {}