kind: Deployment
apiVersion: apps/v1
metadata:
  name: fib-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib-api
  template:
    metadata:
      labels:
        app: fib-api
    spec:
      containers:
      - name: fib-api-container
        image: pfrattezi/fib-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000